#!/usr/bin/env python3
"""Generate the explorer's PRESENTATION CONFIG from the registry: products.js
(the picker table) + per-palette colorbar PNGs, for committing into the main
repo's /satellite/explorer/. One authoring point: a new recipe row in
s2_recipes/s2_registry flows into the viewer by re-running this and committing
the output (the vendored-asset pattern -- the page stays self-contained and
works before the box has emitted anything).

  python s2_products_export.py --out /path/to/Triple-A-Tropics/satellite/explorer
"""
from __future__ import annotations

import argparse
import json
import os

import numpy as np
from PIL import Image

import s2_recipes as X
import s2_registry as R
from colormaps import get_enhancement, enhancement_norm

# Colorbar presentation per FROZEN enhancement: (ticks top->bottom, caption).
# Ticks are display labels inside the norm range (house style: the existing
# explorer rainbow_ir bar shows 40/0/-40/-80).
CBARS = {
    "rainbow_ir": (["40", "0", "−40", "−80"], "Brightness temperature (°C)"),
    "dvorak":     (["40", "0", "−40", "−80"], "Brightness temperature (°C)"),
    "wv_tat":     (["0", "−30", "−60", "−90"], "Brightness temperature (°C)"),
    "grayscale":  (["30", "−10", "−50", "−90"], "Brightness temperature (°C)"),
}
REFL_TICKS = (["100", "50", "0"], "Reflectance (%)")

BAR_W, BAR_H = 14, 230


def render_cbar_png(enhancement: str, path: str):
    """Vertical bar from the FROZEN cmap+norm (vmax at top), matching the
    explorer's existing rainbow_ir_cbar.png geometry."""
    cmap = get_enhancement(enhancement)["cmap"]
    norm = enhancement_norm(enhancement)
    vals = np.linspace(norm.vmax, norm.vmin, BAR_H)
    rgba = (np.asarray(cmap(norm(vals))) * 255 + 0.5).astype(np.uint8)  # H x 4
    img = np.repeat(rgba[:, None, :], BAR_W, axis=1)
    Image.fromarray(img, "RGBA").save(path)


def render_refl_cbar_png(path: str):
    """Reflectance gray bar: display gray = sqrt(reflectance) (the c01-c06
    gamma-2 stretch), 100% at top."""
    r = np.linspace(1.0, 0.0, BAR_H)
    g = (np.sqrt(r) * 255 + 0.5).astype(np.uint8)
    col = np.dstack([g, g, g, np.full_like(g, 255)])[0]      # H x 4
    img = np.repeat(col[:, None, :], BAR_W, axis=1)
    Image.fromarray(img, "RGBA").save(path)


def product_row(e) -> dict:
    r = X.RECIPES_BY_KEY.get(e.recipe_id) if e.recipe_id else None
    if r is None:   # the pre-suite clean-IR row
        title, group, day_only, bt = "C13 · 10.3 µm (Clean IR)", "channel", False, True
        cbar_key = "rainbow_ir"
    else:
        title, group, day_only, bt = r.title, r.group, r.day_only, bool(r.bt_band)
        if r.kind == "single_palette":
            cbar_key = r.enhancement
        elif r.kind == "sandwich":
            cbar_key = "rainbow_ir"      # sandwich colors ARE rainbow_ir hues
        elif r.kind == "rgb_guns" and all(g.kind == "refl" for g in r.guns) \
                and len({g.expr for g in r.guns}) == 1:
            cbar_key = "_refl"           # gray single reflective channel
        else:
            cbar_key = None              # multispectral RGB / truecolor: no scalar bar
    cbar = None
    if cbar_key == "_refl":
        cbar = {"img": "cbars/gray_refl.png", "ticks": REFL_TICKS[0], "cap": REFL_TICKS[1]}
    elif cbar_key:
        ticks, cap = CBARS[cbar_key]
        cbar = {"img": f"cbars/{cbar_key}.png", "ticks": ticks, "cap": cap}
    return {"key": e.band_key, "id": e.product_id, "path": e.product_path,
            "title": title, "group": group, "bt": bt, "dayOnly": day_only,
            "cbar": cbar}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="main-repo satellite/explorer dir")
    ap.add_argument("--sector", default="conus")
    args = ap.parse_args(argv)

    entries = [e for e in R.REGISTRY
               if e.tiled and e.sector_key == args.sector and e.family == "goes"]
    # picker order: the clean-IR default first, then composites, RGBs, channels
    order = {"channel": 2, "rgb": 1, "composite": 0}
    rows = [product_row(e) for e in entries]
    rows.sort(key=lambda p: (p["key"] != "ir", order[p["group"]], p["title"]))

    cdir = os.path.join(args.out, "cbars")
    os.makedirs(cdir, exist_ok=True)
    for name in CBARS:
        render_cbar_png(name, os.path.join(cdir, f"{name}.png"))
    render_refl_cbar_png(os.path.join(cdir, "gray_refl.png"))

    js = ("/* GENERATED by tat-satellite-render s2_products_export.py -- do not\n"
          " * hand-edit. Regenerate after registry/recipe changes:\n"
          " *   python s2_products_export.py --out <TAT>/satellite/explorer\n"
          " * Presentation mirror of the registry suite (SSOT: s2_recipes +\n"
          " * s2_registry); products.json on R2 carries the same rows. */\n"
          "window.TVProducts = " + json.dumps({
              "base": "https://cdn.triple-a-tropics.com/shadow/",
              "sector": args.sector,
              "products": rows,
          }, indent=2, ensure_ascii=False) + ";\n")
    with open(os.path.join(args.out, "products.js"), "w") as f:
        f.write(js)
    print(f"wrote products.js ({len(rows)} products) + {len(CBARS)+1} colorbars -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
